### ISSUE TITLE
No WP-CLI and Admin password is not working

### ISSUE THREAD

**Issue by lucasjahn** [openbridge/wordpress#10]
Hey there,

I bought and installed this stack recently and I have a problem with the setup. So far it worked and the sh script run through as expected. But not the credentials generated in the wordpress-login.txt are not set correctly, so I can't log in with the given password there. Is this due to this setup?

Furthermore, I went into the containers for php-fpm and nginx and there is no installed wp-cli inside the usr/bin. I'm a bit confused because in the repo it said there is everything set up properly and working. So I could install it manually of course and change the image but as I bought this setup I assume everything should be installed correctly as stated in the docs. Could you help me out with this? 

Oh, and I didn't change anything on the sh script or similar. I just ran it, and I worked through it properly without errors. Installed it on a clean fresh Ubuntu instance on my own root server. Letsecnrpyt and Domain DNS are setup fine and working correctly. I can see the frontend without any problem.

**Comment by tspicer** [comment]
Ok, so everything is running except you can not log into wp-admin?

**Comment by lucasjahn** [comment]
Everything is working now. I reinstalled it completely.
