### ISSUE TITLE
Where are the wordpress files located?

### ISSUE THREAD

**Issue by negonix** [openbridge/wordpress#24]
Hello, I cannot find any of the wordpress files after ssh'ing into my host. I am sorry if this is an ignorant question.
thank you.

**Comment by tspicer** [comment]
They are located in the Docker containers

**Comment by negonix** [comment]
> They are located in the Docker containers

Thank you for your reply. If they are in the docker containers, how are they persisting to the hard drive?

**Comment by tspicer** [comment]
Volume mounts

**Comment by negonix** [comment]
thank you
