### ISSUE TITLE
wp admin toolbar cached

### ISSUE THREAD

**Issue by Able2Code** [openbridge/wordpress#6]
Hi @tspicer 
i'm using your php nginx configuration with redis + php fpm images from openbridge git, in many cases when i visit any site page, the cache save also the wp admin toolbar header , by visiting in incognito i can see the cached wp admin toolbar.
this installer will fix my problem? can i use you installer in any vps ?

**Comment by tspicer** [comment]
Hi @Able2Code, see this other issue: https://github.com/openbridge/nginx/issues/43

I updated NGINX HTTP cookie rules as a sample to help people understand how to care for this according to their own installs.
