### ISSUE TITLE
bugs (directive is duplicate & recv() failed (104: Connection reset by peer) )

### ISSUE THREAD

**Issue by lamariabdo** [openbridge/wordpress#8]
Hello @tspicer 
i installed Wordpress Accelerated in amazonaws but i got 2 problems

**first problem** 
```
2019/06/28 13:16:49 [emerg] 1#1: "variables_hash_max_size" directive is duplicate in /etc/nginx/conf.d/botblocker-nginx-settings.conf:18
nginx      | nginx: [emerg] "variables_hash_max_size" directive is duplicate in /etc/nginx/conf.d/botblocker-nginx-settings.conf:18
```
i fix it by commenting **variables_hash_max_size** & **variables_hash_max_size** in nginx.conf

**the second problem**
The plugin  "alidropship" require ioncube and chrome extension, when i try to import from extension to wordpress,  i get 502, i tried to fix it but always same problem.
 i contacted plugin support they said

> The issue is with connection between Google Chrome Extention and nginx of your server, not AliDropship plugin. The Extention transfers the data from Chrome browser external environment to nginx and PHP modules and then to AliDropship plugin.

> Our developers replied that Google Chrome Extention uses admin-ajax.php module, that is why there is a relation between the errors you got and Google Chrome Extention.

this is logs file
```
[error] 1051#1051: *73 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: mythicshop.com, request: "POST /wp-json/alids/v1/extension HTTP/1.1", upstream: "fastcgi://172.24.0.4:9000", host:

"remote_addr": "127.0.0.1", "remote_user": "-", "status": "502", "request": "POST /wp-json/alids/v1/extension HTTP/1.1", "request_uri": "/wp-json/alids/v1/extension", "request_method": "POST", "request_time": "0.100", "request_uri_query": "", "http_referrer": "-", "http_user_agent":
```

**Comment by tspicer** [comment]
Hi @lamariabdo,

This is not a bug, it is something specific to your configuration. 

Are you asking for support related to the configuration of this plugin? We do not offer support testing or development for any third-party plugins.
